### ISSUE TITLE
0.18 Uncaught Error: Unknown template object: function 

### ISSUE THREAD

**Issue by attenzione** [leshill/handlebars_assets#110]
Somewhere here:

    function template(templateSpec, env) {
      /* istanbul ignore next */
      if (!env) {
        throw new Exception("No environment passed to template");
      }
      if (!templateSpec || !templateSpec.main) {
        throw new Exception('Unknown template object: ' + typeof templateSpec);
      }
      ...

**Comment by AlexRiedler** [comment]
okay so I found a way to fix this, and will be implemented in next release! (automatically cleans cache on update of the gem).

**Comment by Breefield** [comment]
Wonderful, thanks Alex!

**Comment by ccmcbeck** [comment]
Thanks, Alex!  This is great news.
