### ISSUE TITLE
Uncaught Error: Unknown template object: function

### ISSUE THREAD

**Issue by vladisakov88** [leshill/handlebars_assets#114]
Hello,

I am trying to run my app after adding a simple template, the same way I added the others templates, and it is give me the following error:
    "Uncaught Error: Unknown template object: function"...
The console shows that "handlebars.js" fails in this point:

```
if (!templateSpec || !templateSpec.main) {
  throw new Exception('Unknown template object: ' + typeof templateSpec);
}
```

I only have to mention that before adding this template everything was fine, now that I deleting this template it is till not working(the same error)...

Please help...

**Comment by AlexRiedler** [comment]
@vladidi is this still an issue in latest release?
 I would also still need more details to replicate
