### ISSUE TITLE
Support handlebars 3!

### ISSUE THREAD

**Issue by badlamer** [leshill/handlebars_assets#115]

**Comment by AlexRiedler** [comment]
will do later today @badlamer ; thanks for the heads up!

**Comment by AlexRiedler** [comment]
didn't get around to it; will see what I can do this weekend.

**Comment by AlexRiedler** [comment]
check out v0.19 @badlamer and see what happens

**Comment by badlamer** [comment]
Not worging after 6fcb5fb5bf0cb6d5beef7352eaa2a2e546db33dd in rails 4.2 .
Working after revert.

**Comment by AlexRiedler** [comment]
@badlamer try again! with 0.19.1 does it work without the revert?

**Comment by badlamer** [comment]
@AlexRiedler working, thanks
