### ISSUE TITLE
Add helper with the handlebars.runtime

### ISSUE THREAD

**Issue by cbou** [leshill/handlebars_assets#120]
I didn't find any way to include helpers when using the handlebars.runtime.

**Comment by AlexRiedler** [comment]
@cbou is this in regards to this gem, or you mean on the javascript side.

**Comment by cbou** [comment]
I means in this gems yes.

When I use `//= require handlebars.runtime`, I don't have the chance to inject helpers before it's compile right?

**Comment by AlexRiedler** [comment]
@cbou it is actually possible to inject by overriding:
- the compiler
- the compiler path
- the known_helpers

I am not sure if there is any documentation about this feature, but it is in there (alpha).

**Comment by mattberridge** [comment]
@AlexRiedler just trying to add a server-side helper I'm using in `Handlebars.registerHelper`. Any code example to implement the above?

Thanks

**Comment by AlexRiedler** [comment]
@mattberridge finally got around to it: https://github.com/AlexRiedler/hbs_examples/tree/helper-example
