### ISSUE TITLE
Check on window breaks IE8/IE9 compatibility

### ISSUE THREAD

**Issue by tagliala** [leshill/handlebars_assets#121]
https://github.com/leshill/handlebars_assets/commit/434358274df058abb1f0109f7d76f477a4d65331#diff-f14ca9959ff06f3ca2ee6b9564866954L26

This change breaks IE8/IE9.

![image](https://cloud.githubusercontent.com/assets/556268/6335552/a0206d84-bb9c-11e4-9bcf-dc7ea0c4e79a.png)

Version 0.18 is fine

More details to come

**Comment by AlexRiedler** [comment]
@tagliala ouch, if you have a better replacement that would be awesome... the problem is handlbars doesn't use a proper wrapper that you can use in a non-window context that is needed for compilation. I could hard-wire in a fix to add that bit of code on the compile though.

**Comment by tagliala** [comment]
@akshayrawat apparently, a `try-catch` block works with IE9 but doesn't work with IE8.

I don't know how to help. Meanwhile I will stick to 0.18

**Comment by AlexRiedler** [comment]
@tagliala I have an idea :)

**Comment by tagliala** [comment]
I also tried `typeof window !== "undefined" && window !== null;` but I got the same error

**Comment by AlexRiedler** [comment]
@tagliala pushed gem version 0.20.0 try it out :)

**Comment by tagliala** [comment]
I confirm it works with both IE8 and IE9

Closed via e1102a795d6d47ef2ce8c26e098c4faa1d7e1291

Thanks! :+1:
