### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property 'partial' of <partial name>

### ISSUE THREAD

**Issue by dougfarre** [leshill/handlebars_assets#123]
I upgraded my rails project from 4.1.8 to 4.2.0 and now I have this error:
 Uncaught TypeError: Cannot assign to read only property 'partial' of  <partial name> on the line below

         options.partial = true;

    __exports__.resolvePartial = resolvePartial;function invokePartial(partial, context, options) {
    options.partial = true;

    if(partial === undefined) {
      throw new Exception("The partial " + options.name + " could not be found");
    } else if(partial instanceof Function) {
      return partial(context, options);
    }
  }

Any suggestions on how to troubleshoot this so I can provide more information would be greatly helpful.  I don't even know where to begin.

**Comment by AlexRiedler** [comment]
@dougfarre did your handlebars_assets version also update?

**Comment by dougfarre** [comment]
Sorry. Im using handlebars_assets 0.20.0
I'm not sure what you mean by other options.  I can post my Gemfile.lock if that would be helpful.

Thanks for your help.

**Comment by dougfarre** [comment]
@AlexRiedler I just manually updated the gem to 0.20.1 and now it is working. Thanks for your help.

**Comment by AlexRiedler** [comment]
@dougfarre okay awesome, I was trying to think about it what could be happening. Thanks for the update!
