### ISSUE TITLE
does it supports new each blocks?

### ISSUE THREAD

**Issue by lancedikson** [leshill/handlebars_assets#127]
Hello, does it supports new `each` blocks with separated contexts?

    {{#each users as |user userId|}}
      Id: {{userId}} Name: {{user.name}}
    {{/each}}

**Comment by AlexRiedler** [comment]
@lancedikson never seen that syntax ; documentation?

**Comment by lancedikson** [comment]
@AlexRiedler http://handlebarsjs.com/block_helpers.html#bloack-params

**Comment by AlexRiedler** [comment]
@lancedikson it should :)
