### ISSUE TITLE
Causes very long load times

### ISSUE THREAD

**Issue by quinn** [leshill/handlebars_assets#136]
A project with many hbs templates can take a very long time to load in development. I wonder if there is an easy way to compile all hbs templates into a single file, rather than individual files?

**Comment by AlexRiedler** [comment]
@quinn it should be linear with the number of templates you have. Merging them into one file should be part of the asset pipeline. I would recommend making sure you are using a relatively recent version for ExecJS to run of v8 or similar. What do you mean by "very long" as well as it is very relative.

**Comment by quinn** [comment]
you're right, it is linear :) and you're also right, this issue isn't really relevant to this project. fwiw, my solution was this:

``` erb
<%= javascript_include_tag 'application' %>
<%= javascript_include_tag 'hbs_views', debug: false %>
```
