### ISSUE TITLE
Bumping handlebars_assets gem version invalidates all assets in manifest.json

### ISSUE THREAD

**Issue by kapowaz** [leshill/handlebars_assets#143]
I've just bumped the version of `handlebars_assets` used in a Rails project, and noticed that it caused every single asset in the manifest.json to be invalidated, even though the overwhelming majority are unchanged (images, CSS, JS not containing Handlebars or any generated template files).

[This line](https://github.com/leshill/handlebars_assets/blob/master/lib/handlebars_assets/engine.rb#L6) seems to be the culprit — it's effectively invalidating all assets by appending the Handlebars version.

Ideally, incrementing the Handlebars version should only result in a change in affected files (which will be determined automatically by Sprockets).

**Comment by AlexRiedler** [comment]
This was fixed a long time back :) closing!
