### ISSUE TITLE
"undefined method `register_engine' for nil" error when using `sprockets-rails` 3

### ISSUE THREAD

**Issue by tjgrathwell** [leshill/handlebars_assets#145]
sprockets-rails 3 was just released, and apparently `app.assets` is now nil at initializer-time, so `app.assets.register_engine` won't work.

One possible solution is to use `config.assets.configure do |env|` instead, which seems to be the more 'proper' way:

```diff
diff --git a/lib/handlebars_assets/engine.rb b/lib/handlebars_assets/engine.rb
index 8a4be6e..c219840 100644
--- a/lib/handlebars_assets/engine.rb
+++ b/lib/handlebars_assets/engine.rb
@@ -2,8 +2,10 @@ module HandlebarsAssets
   # NOTE: must be an engine because we are including assets in the gem
   class Engine < ::Rails::Engine
     initializer "handlebars_assets.assets.register", :group => :all do |app|
-      ::HandlebarsAssets::register_extensions(app.assets)
-      app.assets.version += "#{::HandlebarsAssets::VERSION}"
+      config.assets.configure do |env|
+        ::HandlebarsAssets::register_extensions(env)
+        app.assets.version += "#{::HandlebarsAssets::VERSION}"
+      end
     end
   end
 end
```

Another solution is to use the new `register_transformer` code from https://github.com/leshill/handlebars_assets/pull/135 but relax the constraint on `Sprockets::VERSION` so it also applies to Sprockets 3. The `register_transformer` syntax should work in Sprockets 3 and up, and that code will be needed for Sprockets 4 anyway.

Related issue in the sprockets-rails repo: https://github.com/rails/sprockets-rails/issues/237

**Comment by attenzione** [comment]
have the same issue

**Comment by zedtux** [comment]
@tjgrathwell as I have this issue too, I tried your `sprockets4` branch you did but it's still failing with the some error.

I have then checked the version of sprockets I'm using :

```ruby
irb(main):001:0> Gem::Version.new(Sprockets::VERSION)
=> #<Gem::Version "3.5.2">
```

so it seems that your branch is not compatible with sprockets 3.x.

**Comment by tjgrathwell** [comment]
@zedtux I've added a second PR (#146) with the gem version requirement changed, so if you want you can test using 

```
gem 'handlebars_assets', github: 'tjgrathwell/handlebars_assets', branch: 'sprockets-register-transformers'
```

**Comment by AlexRiedler** [comment]
@tjgrathwell I think master is now in a working state, I still want to do some manual testing over the next week. I have ran against sprockets 3.x and 2.x, it seems to work. I am just not 100% on the rails engine integration at this time.

**Comment by tjgrathwell** [comment]
@AlexRiedler Seems to work for me on all combinations of sprockets-rails 2/3 and sprockets 3/4. Hopefully still works against Sprockets 2.x if you're still interested in that. Good work!

**Comment by zedtux** [comment]
@tjgrathwell your branch `sprockets-register-transformers` works fine.

**Comment by kostia** [comment]
Do you already know, when a release with this fix will be available?

**Comment by sblackstone** [comment]
+1 for @tjgrathwell solution - working fine in both development and production environments..

**Comment by tom-lord** [comment]
+1 the fix looks good to me

As a temporary fix for your application, you can simply lock the `sprockets-rails` version in your Gemfile:

    gem 'sprockets-rails', '~> 2.3'

**Comment by kostia** [comment]
> gem 'sprockets-rails', '~> 2.3'

Not if you need sprockets >= 3…

**Comment by tom-lord** [comment]
@kostia Well no, obviously not. Hopefully a proper fix will be released soon - my suggestion is only a temporary workaround that should be good for the majority of applications.

**Comment by gregblass** [comment]
Perfect time to refactor to react.

**Comment by tjgrathwell** [comment]
@leshill Any word on a new release?

**Comment by badlamer** [comment]
+1

**Comment by AlexRiedler** [comment]
Release of v0.23.0 should fix all your wonderful problems :) Release Today!

**Comment by tjgrathwell** [comment]
Works for me, thanks! :cake:

**Comment by tagliala** [comment]
Thanks!

**Comment by zedtux** [comment]
Awesome, all is now working fine ! Thank you @AlexRiedler :+1:
