### ISSUE TITLE
'app.config.assets.configure' is 'undefined' in 'handlebars_assets/engine.rb'

### ISSUE THREAD

**Issue by happyvig** [leshill/handlebars_assets#162]
What value should be configured in the (gem consuming) Rails (2.3) app's application.rb so that 'app.config.assets.configure' comes defined in engine.rb ?

**Comment by AlexRiedler** [comment]
Rails 2.3 reached EOL on 2013-06-25; I would recommend updating your Rails application.

There might be an old version of handlebars_assets that would support that old version of Rails, but I am uncertain.

**Comment by happyvig** [comment]
Apologies. My mistake. My Rails version is 3.2.22.5

**Comment by happyvig** [comment]
Any specific 'Sprockets' gem version to be used ? I am using  
"sprockets" --> "2.2.3"
"turbo-sprockets-rails3" --> "0.3.14"

**Comment by AlexRiedler** [comment]
@happyvig I would not recommend doing this in public; there is a reason public is different then app/assets/javascripts ; generally using rails and going against convention will be bad news.

the public folder is used for static assets POST compilation; by putting your assets in the folder you may have conflict; and access to public files will be available in most environments (exposed to public).

**Comment by happyvig** [comment]
True. Valid point there.

Question 1 :
Any specific 'Sprockets' gem version to be used when using 'handlebars_assets' v0.23.2 gem ?
I am using `"sprockets" --> "2.2.3"` & `"turbo-sprockets-rails3" --> "0.3.14"`

Question 2 :
And also **template namespace override is not working** when specified via an initializer as
```
HandlebarsAssets.configure do |config|
    config.template_namespace = 'HandlebarsTemplates'
    config.path_prefix = '/public/javascripts/templates'
end
```

or by specifying inside `config/application.rb` as
`HandlebarsAssets::Config.template_namespace = "HBS"`

Appreciate your thoughts about this.

**Comment by AlexRiedler** [comment]
Q1. not that I am aware of; last time I was running with sprockets 3 I believe (its been a long time)

Q2. not sure how that could be happen, and I don't really have time to debug; most of the code is at: https://github.com/leshill/handlebars_assets/blob/master/lib/handlebars_assets/handlebars_template.rb and I believe everywhere is correct for use of template namespace.
