### ISSUE TITLE
Update Handlebars to 4.4.5 or higher for Handlebars Vulnerability

### ISSUE THREAD

**Issue by melissap-nulogy** [leshill/handlebars_assets#174]
There is a vulnerability in Handlebars versions >=4.0.0 <4.4.5 regarding raw block helpers.

**The vulnerability:** https://snyk.io/vuln/SNYK-JS-HANDLEBARS-480388
**The Handlebars issue:** https://github.com/wycats/handlebars.js/issues/1579
**The Handlebars fix:** https://github.com/wycats/handlebars.js/commit/8d5530ee2c3ea9f0aee3fde310b9f36887d00b8b

**Comment by AlexRiedler** [comment]
Upgraded to latest release, which includes v4.5.2 (weirdly enough their website is still 4.4.3)
